### ISSUE TITLE
Custom Schema Option for Parser

### ISSUE THREAD

**Issue by dtothefp** [jonschlinkert/template#13]
Hey Jon, we are implementing YAML tags into into our YAML files in relation to tagging and transforming for translation. In order to do this we need to be able to pass an option down the dependency tree of `parser-front-matter` to attach a SCHEMA to the `js-yaml` [parser]( https://github.com/nodeca/js-yaml/blob/master/examples/custom_types.js#L79). Wondering if you guys could offer support in `pasrser-front-matter`/template/assemble for this or if you could recommend an implementation?

**Comment by jonschlinkert** [comment]
I think we can close this since it was addressed on assemble (correct?). Please feel free to reopen if this is still something we want to explore
