### ISSUE TITLE
Post Render middleware and cloned template object.

### ISSUE THREAD

**Issue by doowb** [jonschlinkert/template#14]
[This section of code](https://github.com/jonschlinkert/template/blob/master/index.js#L1888-L1907) is what I'm referring to here:

 - Before rendering a template object, we're cloning it so we can allow rendering a template multiple times with different data (mostly for partials).
 - After the content is rendered, the `cloned` template is updated with the rendered content and passed to any `postRender` middleware to allow modifying the content if needed.
 - When `postRender` is done, the `cloned.content` is passed back to the caller.

This makes it so users that want to modify something else in a `postRender` middleware can't because the changes only affect the cloned object and are lost. The common case for this is changing `path` after rendering.

Should we allow changing other properties in `postRender`? I think the better way to do it is in `preRender` since the properties will be updated for use during the rendering process.

**Comment by jonschlinkert** [comment]
> This makes it so users that want to modify something else in a postRender middleware can't because the changes only affect the cloned object and are lost.

What are the common use cases for passing the `cloned.content` back to the caller? Either way I think we should ensure that middleware can modify properties post render.

**Comment by doowb** [comment]
Passing the `cloned.content` is the actual value returned when doing either `var content = template.render()` or `template.render(function (err, content) { ... });`.

We're going to have to basically do a "clone" on the cloned object to get all the changed properties to sync with the template object and make sure that the content doesn't change on the original template object, but still return the cloned content string.

Actually, this might not be an issue now that the templates are pre-compiled. Cloning was added before that was in there to ensure the partials can be rendered multiple times. Now that they get pre-compiled, the original `template.content` can be updated and it won't be affected because the compiled piece will still be there on `template.fn`.

I'll try out some things and let you know.

**Comment by jonschlinkert** [comment]
That's exactly what I was wondering, about the compiled functions. thanks for clarifying
