### ISSUE TITLE
Allow hash to be passed via "partial"

### ISSUE THREAD

**Issue by avr** [jonschlinkert/template#29]
In Handlebars 3.0 you can [pass parameters](http://handlebarsjs.com/partials.html#partial-parameters) to a partial like this:

```
{{> photo image_size="100x100" class="pull-left" }}
```

I'd like to use the "partial" helper/keyword like this:

```
{{ partial "photo" image_size="100x100" class="pull-left" }}
```

From what I can tell, somewhere along the line in Template, the `locals.hash` property is getting dropped and not passed into the partial.  Maybe it's also in `engine-assemble`.  I think I've asked about `mergeContext` in another thread - I just can't seem to follow the `renderTemplate` path.  Sorry!

I'm using `assemble` and would like to `assemble.create` various partial/layout types and use the keyword so that it's a little more obvious to other users what's going on.

**Comment by doowb** [comment]
This is possible, but will require some updates to our default helpers (e.g. `{{partial}}`). We've been refactoring template to make it easier to get templates ("views") and understand how the context is merged and presented in the templates. I think the `options.hash` will just be another context source that can be handled.

**Comment by avr** [comment]
Cool - thanks for the reply.  I'll keep an eye on the changes here as you guys keep working on it.

As always - thanks for all the work you've done here and with Assemble.

**Comment by jonschlinkert** [comment]
> This is possible, but will require some updates to our default helpers (e.g. {{partial}}).

@doowb seems like it should be possible to just override the built-in helper with a custom `partial` helper that merges the context however you want. right?

**Comment by doowb** [comment]
Yeah, you can just override it too.
