### ISSUE TITLE
RangeError when rendering templates

### ISSUE THREAD

**Issue by avr** [jonschlinkert/template#32]
First off - I know you guys are busy working on refactoring `template` so maybe this won't matter.

I'm using v0.6.0-beta5 of Assemble and I have a set of files that work as expected on the first pass.

When the watch task re-runs, I keep running into `Maximum call stack size exceeded`.  The actual error message is from `template-render`:

    [09:59:08] 'html' errored after 436 ms
    [09:59:08] RangeError in plugin 'template-render'
    Message:
        Maximum call stack size exceeded

If I use `DEBUG=template:err assemble`, I eventually get:

````
[10:03:29] Starting 'html'...
  template:err renderAsync [catch]: {} +0ms
  template:err renderAsync [helpers]: {} +0ms
  template:err renderAsync [helpers]: {} +1ms
[10:03:30] 'html' errored after 440 ms
[10:03:30] RangeError in plugin 'template-render'
Message:
    Maximum call stack size exceeded
````

Which leads me to `template`.

My questions: is there a better way to debug this? Are there common areas that may cause something like this?

Unfortunately, my repo is private but I can invite you if you have time/space to take a quick look.

**Comment by jonschlinkert** [comment]
very sorry for the delay! I need to stop viewing these on my phone, I have no idea how to see notifs that have been cleared in github... 

If you're still having the issue, I'd be happy to take a look. again I'm really sorry for taking so long to reply. 

(if it's any consolation, template has been completely from the ground up and it's running better than ever, it's faster, and this should be solved as well. even better, I think we wrapped up the refactoring today! and we're almost done updating assemble based on the changes.)

**Comment by avr** [comment]
Jon - no worries at all.

If you think Assemble will be updated soon - I can just hold off and revisit this.  I noticed your sandbox: https://github.com/jonschlinkert/template-sandbox which made me think things are getting close.

I'm not actually doing much with Assemble beyond layouts, partials, and includes.  Do you have some quick thoughts on what Assemble adds beyond Template?

**Comment by jonschlinkert** [comment]
> Do you have some quick thoughts on what Assemble adds beyond Template?

there are some things in `template-sandbox` that neither `template` nor `assemble` will do... like converting liquid templates to handlebars... :)  Also, `template` has several methods that will be moved out and either published as a lib or moved to assemble. 

In general though, Template will provide methods for handling collections, collection items, routes, middleware, template engines and helpers, etc. Also Template will never have a CLI.

Assemble will continue to provide higher level methods for initializing and building projects, configuration, working with the file system, data resolution, path handling and so on. 

Assemble will also have much more emphasis on generating things via CLI, and will have API and CLI methods for the following:

- `boilerplate`: which are "complete" generalized projects
- `generate`: which generates a project from a boilerplate
- `scaffold`: can be thought of as "templates to be used for generating templates". Whereas a boilerplate's lifecycle ends when a project is generated, scaffolds can continue to be used throughout development. For example, `assemble new page` will generate a new `page` (or `layout` or `partial` or even a custom collection item) based on a pre-defined "scaffold"

Thoughts? how does this sound so far?

**Comment by avr** [comment]
Jon - this is great.  Thanks for the detailed explanation and I hope I didn't miss it somewhere else.  You guys are doing so much it's hard to keep up :)

The idea of scaffolds/generators is terrific - and actually perfect for us.  I've built out a framework of layouts and partials that we use as a starting point internally.  We've wanted to make our "framework" available for other departments - but a scaffolding API would be incredible and much easier for others to start and use.

I've had trouble groking Assemble (and node/npm in general).  BUT - if I can figure it out and provide scaffolding, it will lower the barrier for others.

This sounds really, really great.

**Comment by jonschlinkert** [comment]
awesome! we're hoping to make assemble easier to pick up and use without having to be a full-time programmer... definitely feel free to ask questions any time!

**Comment by avr** [comment]
Hey Jon...I'm still bumping into this range error and can't track down the culprit.

Would be able to take a quick look?

**Comment by jonschlinkert** [comment]
yeah sure, let me know how I can help

**Comment by avr** [comment]
Okay - I've added you to my private repo.

The error pops up when you run `assemble` and then save a few page templates in `src/iucomm/templates/pages/*.hbs`

**Comment by jonschlinkert** [comment]
damn, I didn't see this reply, I'm so sorry. if it's any consolation we're trying to get assemble updated with this tonight. so the issue will hopefully be fixed anyway.

**Comment by avr** [comment]
Ha - no worries at all.

I ended up removing all calls to `{{ partial "xxxx" }}` and things work just fine.  I think it was an issue with the default `asyncHelpers` in Template and calls to `resolveHelper` in `helper-cache`.

I've been keeping an eye on the Assemble/Template ecosystem and knew stuff was coming so I haven't been worried about it.

**Comment by jonschlinkert** [comment]
ok good to hear! I promise I'll be more on top of existing issues once we get these massive releases stabilized!
