### ISSUE TITLE
`sync` render method

### ISSUE THREAD

**Issue by iulo** [jonschlinkert/template#36]
any way?

**Comment by tunnckoCore** [comment]
try to use https://github.com/jonschlinkert/templates (notice the final "s"), it more up-to-date and if i'm not wrong is almost the same.

**Comment by jonschlinkert** [comment]
> There's .renderSync in templates lib

is there? honestly I don't remember but I didn't think there was. 

fwiw the reason we don't support sync rendering anymore is that middleware needs to be async, and we support async helpers. 

thanks @tunnckoCore

**Comment by tunnckoCore** [comment]
> @jonschlinkert is there? honestly I don't remember but I didn't think there was.
