### ISSUE TITLE
helper options

### ISSUE THREAD

**Issue by jonschlinkert** [jonschlinkert/template#6]
I think we need to have an option or property somewhere dedicated to _helper options_.

Currently we're just winging it:

```js
var extend = require('extend-shallow');

template.helper('foo', function (options) {
  var opts = extend({}, this.app.options, options);
  // do stuff
});
```

It's awesome how easy it is to pass options to helpers, but those options shouldn't be mixed in with the general/global options.

Of course, any helper author can namespace the helper's options however they see fit, but I'd really prefer to have a convention for doing it.

**Comment by doowb** [comment]
All `options` are passed into helpers now as `this.options`. Can this be closed or should the code be updated to only pass in options that match the helper name?

**Comment by akileez** [comment]
Sorry to interject but just for my understanding ...by doing the following ...

```js
exports.somehelper = function (body, options, locals) {
  // this.options are options for this particular helper ???
  options = extend(Array.prototype.pop.call(arguments), this.options,  locals);
...
}
```
only affects this  particular helper if I define options for it? It does not mess with `locals` in anyway? doesn't seem like it but I just want to confirm. I use the hell out of locals in all my helpers. any significant alternation means I need to adjust ...

**Comment by doowb** [comment]
No, the options don't mess with any locals that you're passing into the helper.

**Comment by akileez** [comment]
thanks @doowb  for the confirm.

**Comment by jonschlinkert** [comment]
closing since this is possible out-of-the-box
